project_name: skeleton
stage_name: local
services:
  webserver:
    container_name: webserver
    image: yejune/webserver:7.0.14t
    expose:
      - '80'
    working_dir: /var/www
    environment:
      USE_SSL: on
      FPM_LISTEN: /dev/shm/php-fpm.sock
      FASTCGI_PASS: unix:/dev/shm/php-fpm.sock
  memcached:
    container_name: memcached
    image: jinwoo/memcached:1.4.25
    expose:
      - '11211'
  redis:
    container_name: redis
    image: jinwoo/redis:3.2.0
    expose:
      - '6379'
  beanstalk:
    container_name: beanstalk
    image: jinwoo/beanstalk:1.10
    expose:
      - '11300'
stages:
  local:
    services:
      mysql:
        container_name: mysql
        image: yejune/mysql
        expose:
          - '3306'
        environment:
          TZ: Asia/Seoul
          MYSQL_URL: 'mysql://user:pass@mysql:3306'
          MYSQL_ROOT_PASSWORD: root
          DOMAIN: mysql.local.com
          INITDB: |
            CREATE DATABASE IF NOT EXISTS `WORKSPACE`;
        volumes:
          - './var/mysql:/var/lib/mysql'
      webserver:
        hostname: local.com
        volumes:
          - '.:/var/www'
          - './var/log/nginx:/var/log/nginx'
          - './var/certs:/var/certs'
        environment:
          DOMAIN: local.com
          STAGE_NAME: local
          DEBUG: 1
          MASTER_DATABASE_URL: mysql://root:root@mysql:3306/WORKSPACE
          SLAVE1_DATABASE_URL: mysql://root:root@mysql:3306/WORKSPACE
        links:
          - mysql
          - memcached
          - redis
  production:
    services:
      webserver:
        environment:
          DOMAIN: production.com
          STAGE_NAME: production
          DEBUG: 0
          MASTER_DATABASE_URL: mysql://root:rootroot@dbmaster.ca7pezyjeax2.ap-northeast-2.rds.amazonaws.com:3306/WORKSPACE
          SLAVE1_DATABASE_URL: mysql://root:rootroot@dbslave1.ca7pezyjeax2.ap-northeast-2.rds.amazonaws.com:3306/WORKSPACE
      links:
        - memcached
        - redis
tasks:
  composer:
    container: webserver
    cmd: composer
  phinx:
    container: webserver
    cmd: vendor/bin/phinx
  devtools:
    container: webserver
    cmd: vendor/bin/phalcon.php
